### ISSUE TITLE
"cookieConsent.administration.applications" remains in the Applications panel after the app is Uninstalled 

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-cookie-consent#15]
Steps to reproduce:

1. Install the app on Main or subwiki simple or on farm
2. Make changes to the Cookie setup eg. change colors, text
3. Save the changes
4. Uninstall the Cookie app
5. Observe the Applications panel

Expected results: The Cookie app is removed from the Applications panel once uninstalled.

Actual results:  The Cookie app still remains in the Applications panel as "cookieConsent.administration.applications". This can be seen as Admin / simple user / guest.

Environment: Windows 10, XWiki 10.11.1 with MySQL 5.7 and Edge 18

![maincookieafteruninstal](https://user-images.githubusercontent.com/40691112/51838782-0a412080-2310-11e9-83b5-9fca501d5050.jpg)
![subcookieafteruninstal](https://user-images.githubusercontent.com/40691112/51838783-0a412080-2310-11e9-9489-9e777bf8160f.jpg)
![subchangescookie](https://user-images.githubusercontent.com/40691112/51838784-0a412080-2310-11e9-91db-0f2f66845cb8.jpg)

**Comment by acotiuga** [comment]
This issue occurs because the homepage of the application holds both the UIExtension object and the Configuration object exposed in Administration. When a page is modified, the Extension manager excludes it at uninstall. In this case all the pages (including translations) are removed but the WebHome is kept. The solution is to have separated  pages for the objects.

**Comment by CamiAndrei** [comment]
This issue is not present anymore, since the extension is not displayed anymore in the Applications panel, but only in the Other section from the Administration, starting with the version 1.2.4.
